name: fresh-tech
services:
  # client:
  # build:
  #   context: ./client
  #   dockerfile: Dockerfile
  # ports:
  #   - "3000:3000"
  # volumes:
  #   - ./client:/app
  # environment:
  #   - REACT_APP_API_URL=http://localhost:5000
  # depends_on:
  #   - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8475"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/fresh-tech
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6378:6379"
